name: PROJECT_NAME
services:
  FRAMEWORK:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ../..:/workspaces:cached
      - apt-cache:/var/cache/apt/archives/
      # - ~/.zsh_history:/home/vscode/.zsh_history
      # - ~/.zshrc:/home/vscode/.zshrc
    command: sleep infinity
    user: vscode
    environment:
      - SHELL=/bin/zsh
    # Uncomment the next line if you want to add more services
    # network_mode: service:db
    # Uncomment if you want to add a database service
    depends_on:
      - postgres
  
  postgres:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres

volumes:
  apt-cache:
  postgres-data:
